apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zabbix-server.fullname" . }}
  labels:
    {{- include "zabbix-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "zabbix-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zabbix-server.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "zabbix-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
{{- range $key, $value := .Values.extraVars }}
          - name: {{ $key }}
            value: {{ $value }}
{{- end }}
          ports:
            - name: "10051"
              containerPort: 10051
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 10051
          readinessProbe:
            tcpSocket:
              port: 10051 
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
